config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :servicos
  resources :contratos
  resources :trabalhadors
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'welcome#index'
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :contratoes
  has_many :servicos, through: :contratoes

  validates :nome_completo, presence: {message: 'Nome completo obrigatório'}, format: {with: /\A[a-zA-z ]+\z/}, length: {minimum: 8, maximum: 80}
  validates :data_de_nascimento, presence: {message: 'Data de nascimento obrigatória'}
  validates :cpf, presence: {message: 'CPF obrigatório'}, length: {minimum: 11, maximum: 11}, numericality: {only_integer: true}, uniqueness: true
  validates :email, presence: {message: 'E-mail obrigatório'}, format: {with: URI:: MailTo::EMAIL_REGEXP}, uniqueness: true
  validates :telefone, presence: {message: 'Telefone para contato obrigatório'}, length: {is: 11, message: 'Precisa ter 11 dígitos'}
  validates :logradouro, presence: true, length: {maximum: 40}
  validates :complemento, presence: true, length: {maximum: 40}
  validates :bairro, presence: true, length: {maximum: 40}, format: { with: /\A[a-zA-z ]+\z/}
  validates :cidade, presence: true, length: {maximum: 40}, format: { with: /\A[a-zA-z ]+\z/}
  validates :cep, presence: true, length: {minimum:8, maximum: 8}, numericality: {only_integer: true}
  validates :senha, presence: {message: 'Senha obrigatória'}, length: {minumum: 5, maximum: 20}, uniqueness: true
  validate :valida_data

  def valida_data
    if data_de_nascimento.present? && data_de_nascimento > Time.zone.today
      errors.add(:data_de_nascimento, "A data deve ser a de hoje ou anterior")
    end
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome_completo, :data_de_nascimento, :cpf, :email, :telefone, :logradouro, :complemento, :bairro, :cidade, :cep, :senha)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Nome completo:</strong>
    <%= cliente.nome_completo %>
  </p>

  <p>
    <strong>Data de nascimento:</strong>
    <%= cliente.data_de_nascimento %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= cliente.cpf %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= cliente.email %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= cliente.telefone %>
  </p>

  <p>
    <strong>Logradouro:</strong>
    <%= cliente.logradouro %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= cliente.complemento %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= cliente.bairro %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= cliente.cidade %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= cliente.cep %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= cliente.senha %>
  </p>

</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<style>
  div{
      margin-bottom: 10px;
  }
</style>
  <div class="form">
  <div>
    <%= form.label :nome_completo, style: "display: block" %>
    <%= form.text_field :nome_completo %>
  </div>

  <div>
    <%= form.label :data_de_nascimento, style: "display: block" %>
    <%= form.date_field :data_de_nascimento %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :logradouro, style: "display: block" %>
    <%= form.text_field :logradouro %>
  </div>

  <div>
    <%= form.label :complemento, style: "display: block" %>
    <%= form.text_field :complemento %>
  </div>

  <div>
    <%= form.label :bairro, style: "display: block" %>
    <%= form.text_field :bairro %>
  </div>

  <div>
    <%= form.label :cidade, style: "display: block" %>
    <%= form.text_field :cidade %>
  </div>

  <div>
    <%= form.label :cep, style: "display: block" %>
    <%= form.text_field :cep %>
  </div>

  <div>
    <%= form.label :senha, style: "display: block" %>
    <%= form.text_field :senha %>
  </div>

  <div>
    <%=form.submit %>
  </div>
<% end %>
</div>

app/views/clientes/edit.html.erb
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
      }
      input[type="submit" i]{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
</head>

<body>
<header>
  <div class="flex-container menu">
    <div><h1>Editar Cliente</h1></div>
  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li> <%= render "form", cliente: @cliente %></li>
      <li class="btn"><%= link_to "Ver todos os Clientes", clientes_path %></li>
    </ul>
  </div>
</div>
</body>

app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;
          margin-top: 30px;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          text-decoration: none;
      }
      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
<body>
<header>
  <div class="flex-container menu">
    <div><h1>Clientes</h1></div>
    <ul class="list-items">
      <h2>
        <li><a><%= link_to "Ver Contratos", contratos_path %></a></li>
      </h2>
    </ul>

  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <div id="clientes">
        <li class="btn"><%= link_to "Voltar a Pagina Inicial", root_path %></li>
        <li class="btn"><%= link_to "Criar Cliente", new_cliente_path %></li>
        <% @clientes.each do |cliente| %>
          <%= render cliente %>
          <li class="btn"><%= link_to "Mostrar esse Cliente", cliente %></li>
        <% end %>
      </div>
    </ul>
  </div>
</div>
</body>

app/views/clientes/new.html.erb
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      .btn {
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
      }
      input[type="submit" i]{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
</head>

<body>
<header>
  <div class="flex-container menu">
    <div><h1>Novo Cliente</h1></div>
  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li> <%= render "form", cliente: @cliente %></li>
    </ul>
  </div>
</div>
</body>

app/views/clientes/show.html.erb
<p style="color: green"><%= notice %></p>

<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          height: 100vh;
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      button{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;
      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          text-decoration: none;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
<body>
<header>
  <div class="flex-container menu">
    <div>
      <ul class="list-items">
      <h1>
        <li><a><%= link_to "GServicesES", root_path%></a></li>
      </h1>
      </ul>
    </div>

  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li> <%= render @cliente %></li>
      <li class="btn"><%= link_to "Editar esse Cliente", edit_cliente_path(@cliente)%></li>
      <li class="btn"><%= link_to "Ver todos os Clientes", clientes_path %></li>
      <li><%= button_to "Apagar esse Cliente", @cliente, method: :delete%></li>
    </ul>
  </div>
</div>
</body>