config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :servicos
  resources :contratos
  resources :trabalhadors
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'welcome#index'
end

app/models/administrador.rb
class Administrador < ApplicationRecord

  validates :nome_completo, presence: {message: 'Nome completo obrigatório'}, format: {with: /\A[a-zA-Z ]+\Z/}, length: {minimum: 8, maximum: 80}
  validates :data_de_nascimento, presence: {message: 'Data de nascimento obrigatória'}
  validates :email, presence: {message: 'E-mail obrigatório'}, format: {with: URI:: MailTo::EMAIL_REGEXP}, uniqueness: true
  validates :telefone, presence: {message: 'Telefone para contato obrigatório'}, length: {is: 11, message: 'Precisa ter 11 dígitos'}
  validates :senha, presence: {message: 'Senha obrigatória'}, length: {minumum: 5, maximum: 20}, uniqueness: true

  validate :valida_data

  def valida_data
    if data_de_nascimento.present? && data_de_nascimento > Time.zone.today
      errors.add(:data_de_nascimento, "A data deve ser a de hoje ou anterior")
    end
  end

end

app/controllers/administradors_controller.rb
class AdministradorsController < ApplicationController
  before_action :set_administrador, only: %i[ show edit update destroy ]

  # GET /administradors or /administradors.json
  def index
    @administradors = Administrador.all
  end

  # GET /administradors/1 or /administradors/1.json
  def show
  end

  # GET /administradors/new
  def new
    @administrador = Administrador.new
  end

  # GET /administradors/1/edit
  def edit
  end

  # POST /administradors or /administradors.json
  def create
    @administrador = Administrador.new(administrador_params)

    respond_to do |format|
      if @administrador.save
        format.html { redirect_to administrador_url(@administrador), notice: "Administrador was successfully created." }
        format.json { render :show, status: :created, location: @administrador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradors/1 or /administradors/1.json
  def update
    respond_to do |format|
      if @administrador.update(administrador_params)
        format.html { redirect_to administrador_url(@administrador), notice: "Administrador was successfully updated." }
        format.json { render :show, status: :ok, location: @administrador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradors/1 or /administradors/1.json
  def destroy
    @administrador.destroy

    respond_to do |format|
      format.html { redirect_to administradors_url, notice: "Administrador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrador
      @administrador = Administrador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrador_params
      params.require(:administrador).permit(:nome_completo, :data_de_nascimento, :email, :telefone, :senha)
    end
end

app/helpers/administradors_helper.rb
module AdministradorsHelper
end

app/views/administradors/_administrador.html.erb
<div id="<%= dom_id administrador %>">
  <p>
    <strong>Nome completo:</strong>
    <%= administrador.nome_completo %>
  </p>

  <p>
    <strong>Data de nascimento:</strong>
    <%= administrador.data_de_nascimento %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= administrador.email %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= administrador.telefone %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= administrador.senha %>
  </p>

  
</div>

app/views/administradors/_form.html.erb
<%= form_with(model: administrador) do |form| %>
  <% if administrador.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(administrador.errors.count, "error") %> prohibited this administrador from being saved:</h2>

      <ul>
        <% administrador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome_completo, style: "display: block" %>
    <%= form.text_field :nome_completo %>
  </div>

  <div>
    <%= form.label :data_de_nascimento, style: "display: block" %>
    <%= form.date_field :data_de_nascimento %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :senha, style: "display: block" %>
    <%= form.text_field :senha %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/administradors/edit.html.erb
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 250px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
      }
      input[type="submit" i]{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
</head>

<body>
<header>
  <div class="flex-container menu">
    <div><h1>Editar Administrador</h1></div>
  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li> <%= render "form", administrador: @administrador %></li>
      <li class="btn"><%= link_to "Ver todos os Administradores", administradors_path %></li>
    </ul>
  </div>
</div>
</body>

app/views/administradors/index.html.erb
<p style="color: green"><%= notice %></p>

<p style="color: green"><%= notice %></p>

<p style="color: green"><%= notice %></p>
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
      }
      .list-items li strong a{
          color: white;
          padding: 10px;
          display: block;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;
          margin-top: 30px;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          text-decoration: none;
      }
      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
<body>
<header>
  <div class="flex-container menu">
    <div><h1>Administradores</h1></div>
    <ul class="list-items">
      <li><strong> <a class="links_adm"><%= link_to "Ver Servicos", servicos_path %></a></strong></li>
        <li><strong><a class= "links_adm"><%= link_to "Ver Contratos", contratos_path %></a></strong> </li>
        <li><strong><a class= "links_adm"><%= link_to "Ver Clientes", clientes_path %></a></strong></li>
        <li><strong><a class= "links_adm"><%= link_to "Ver Tabalhadores", trabalhadors_path %></a></strong> </li>
    </ul>

  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <div id="administradors">
        <li class="btn"><%= link_to "Voltar a Pagina Inicial", root_path %></li>
        <li class="btn"><%= link_to "Criar Administrador", new_administrador_path %></li>
        <% @administradors.each do |administrador| %>
          <%= render administrador %>
          <li class="btn"><%= link_to "Mostrar Administrador", administrador %></li>
        <% end %>
      </div>
    </ul>
  </div>
</div>
</body>

app/views/administradors/new.html.erb
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      input[type="submit" i]{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 250px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
</head>

<body>
<header>
  <div class="flex-container menu">
    <div><h1>Novo Administrador</h1></div>
  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li> <%= render "form", administrador: @administrador %></li>
      <li class="btn">  <%= link_to "Ver todos os Administradores", administradors_path %></li>
    </ul>
  </div>
</div>
</body>




<br>

<div>

</div>

app/views/administradors/show.html.erb
<p style="color: green"><%= notice %></p>

<p style="color: green"><%= notice %></p>
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          height: 100vh;
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 250px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          text-decoration: none;
      }
      button{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 250px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
<body>
<header>
  <div class="flex-container menu">
    <div>
      <ul class="list-items">
        <h1>
          <li><a><%= link_to "GServicesES", root_path%></a></li>
        </h1>
      </ul>
    </div>

  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li> <%= render @administrador %></li>
      <li class="btn"><%= link_to "Editar Administrador", edit_administrador_path(@administrador) %></li>
      <li class="btn"><%= link_to "Ver todos os Administradores", administradors_path %></li>
      <li><%= button_to "Apagar Administrador", @administrador, method: :delete %></li>
    </ul>
  </div>
</div>
</body>
</div>