config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :servicos
  resources :contratos
  resources :trabalhadors
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          height: 100vh;
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
</head>

<body>
<header>
  <div class="flex-container menu">
    <div><h1>GServicesES</h1></div>
    <ul class="list-items">
      <li><a href="https://github.com/GServicesES/GServicesES" target="_blank">Github</a></li>
      <li><a><%=link_to 'Adiministrador', administradors_path %></a></li>
    </ul>
  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li class="btn"> <%=link_to 'Cadastrar Cliente', new_cliente_path %></li>
      <li class="btn"> <%=link_to 'Cadastrar Trabalhador', new_trabalhador_path %></li>
      <li class="btn"> <%=link_to 'Cadastrar Contrato', new_contrato_path %></li>
      <li class="btn"> <%=link_to 'Cadastrar Servico', new_servico_path %></li>
      <li class="btn"><%= link_to "Ver todos os Clientes", clientes_path %></li>
      <li class="btn"><%= link_to "Ver todos os Trabalhadores", trabalhadors_path %></li>
    </ul>
  </div>
</div>
</body>