config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :servicos
  resources :contratos
  resources :trabalhadors
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'welcome#index'
end

app/models/trabalhador.rb
class Trabalhador < ApplicationRecord

  has_many :servicos, dependent: :destroy
  has_many :contratoes, through: :servicos

  validates :nome_completo, presence: {message: 'Nome completo obrigatório'}, format: {with: /\A[a-zA-z ]+\z/}, length: {minimum: 8, maximum: 80}
  validates :data_de_nascimento, presence: {message: 'Data de nascimento obrigatória'}
  validates :email, presence: {message: 'E-mail obrigatório'}, format: {with: URI:: MailTo::EMAIL_REGEXP}, uniqueness: true
  validates :telefone, presence: {message: 'Telefone para contato obrigatório'}, length: {is: 11, message: 'Precisa ter 11 dígitos'}
  validates :profissao, presence: {message: 'Campo Profissão obrigatório'}, length: {maximum: 40}
  validates :senha, presence: {message: 'Senha obrigatória'}, length: {minumum: 5, maximum: 20}, uniqueness: true

end

app/controllers/trabalhadors_controller.rb
class TrabalhadorsController < ApplicationController
  before_action :set_trabalhador, only: %i[ show edit update destroy ]

  # GET /trabalhadors or /trabalhadors.json
  def index
    @trabalhadors = Trabalhador.all
  end

  # GET /trabalhadors/1 or /trabalhadors/1.json
  def show
    @trabalhador = Trabalhador.all.where(id:params[:id]).first
  end

  # GET /trabalhadors/new
  def new
    @trabalhador = Trabalhador.new
  end

  # GET /trabalhadors/1/edit
  def edit
  end

  # POST /trabalhadors or /trabalhadors.json
  def create
    @trabalhador = Trabalhador.new(trabalhador_params)

    respond_to do |format|
      if @trabalhador.save
        format.html { redirect_to trabalhador_url(@trabalhador), notice: "Trabalhador was successfully created." }
        format.json { render :show, status: :created, location: @trabalhador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trabalhador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabalhadors/1 or /trabalhadors/1.json
  def update
    respond_to do |format|
      if @trabalhador.update(trabalhador_params)
        format.html { redirect_to trabalhador_url(@trabalhador), notice: "Trabalhador was successfully updated." }
        format.json { render :show, status: :ok, location: @trabalhador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trabalhador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabalhadors/1 or /trabalhadors/1.json
  def destroy
    @trabalhador.destroy

    respond_to do |format|
      format.html { redirect_to trabalhadors_path, notice: "Trabalhador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete
    @trabalhador = Trabalhador.where("id = ?", params[:id]).first
    @trabalhador.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Trabalhador was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabalhador
      @trabalhador = Trabalhador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trabalhador_params
      params.require(:trabalhador).permit(:nome_completo, :data_de_nascimento, :email, :telefone, :profissao, :senha)
    end
end

app/helpers/trabalhadors_helper.rb
module TrabalhadorsHelper
end

app/views/trabalhadors/_form.html.erb
<%= form_with(model: trabalhador) do |form| %>
  <% if trabalhador.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trabalhador.errors.count, "error") %> prohibited this trabalhador from being saved:</h2>

      <ul>
        <% trabalhador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome_completo, style: "display: block" %>
    <%= form.text_field :nome_completo %>
  </div>

  <div>
    <%= form.label :data_de_nascimento, style: "display: block" %>
    <%= form.date_field :data_de_nascimento %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :profissao, style: "display: block" %>
    <%= form.text_field :profissao %>
  </div>

  <div>
    <%= form.label :senha, style: "display: block" %>
    <%= form.text_field :senha %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trabalhadors/_trabalhador.html.erb
<div id="<%= dom_id trabalhador %>">
  <p>
    <strong>Nome completo:</strong>
    <%= trabalhador.nome_completo %>
  </p>

  <p>
    <strong>Data de nascimento:</strong>
    <%= trabalhador.data_de_nascimento %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= trabalhador.email %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= trabalhador.telefone %>
  </p>

  <p>
    <strong>Profissao:</strong>
    <%= trabalhador.profissao %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= trabalhador.senha %>
  </p>

</div>

app/views/trabalhadors/edit.html.erb
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
      }
      input[type="submit" i]{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
</head>

<body>
<header>
  <div class="flex-container menu">
    <div><h1>Editar Trabalhador</h1></div>
  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li> <%= render "form", trabalhador: @trabalhador %></li>
      <li class="btn"><%= link_to "Ver Todos Trabalhadores", trabalhadors_path %></li>
    </ul>
  </div>
</div>
</body>



<br>

<div>

</div>

app/views/trabalhadors/index.html.erb
<p style="color: green"><%= notice %></p>

<p style="color: green"><%= notice %></p>

<p style="color: green"><%= notice %></p>
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;
          margin-top: 30px;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          text-decoration: none;
      }
      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
<body>
<header>
  <div class="flex-container menu">
    <div><h1>Trabalhadores</h1></div>
    <ul class="list-items">
      <h2>
        <li><a><%= link_to "Ver Servicos", servicos_path %></a></li>
      </h2>
    </ul>

  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <div id="trabalhadors">
        <li class="btn"><%= link_to "Voltar a Pagina Inicial", root_path %></li>
        <li class="btn"><%= link_to "Criar Trabalhador", new_trabalhador_path %></li>
        <% @trabalhadors.each do |trabalhador| %>
          <%= render trabalhador %>
          <li class="btn"><%= link_to "Mostrar esse Trabalhador", trabalhador %></li>
        <% end %>
      </div>
    </ul>
  </div>
</div>
</body>

app/views/trabalhadors/new.html.erb
<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
      }
      input[type="submit" i]{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
</head>

<body>
<header>
  <div class="flex-container menu">
    <div><h1>Novo Trabalhador</h1></div>
  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <%= render "form", trabalhador: @trabalhador %>
    </ul>
  </div>
</div>
</body>

app/views/trabalhadors/show.html.erb
<p style="color: green"><%= notice %></p>

<head>
  <style>
      *{
          margin: 0;
          padding: 0;
          font-family: 'Open Sans', sans-serif;
      }

      ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }
      ul li a{
          text-decoration: none;
      }

      .flex-container{
          display: flex;
          max-width: 992px;
          margin: auto;
          width: 100%;
          min-width: 320px;
      }

      header{
          background-color: darkblue;
          height: 100px;
          display: flex;
          align-items: center;
          color: white;
          margin-bottom: 8px;
      }
      header .list-items{
          display: flex;
          width: 100%;
          max-width: 260px;
          justify-content: space-between;
          align-items: center;
      }
      .list-items li a{
          color: white;
      }

      header .menu{
          justify-content: space-between;
      }
      .apresentação{
          height: 100vh;
          align-items: center;
          justify-content: space-between;
      }
      .apresentação .texto-apresentação{
          min-height: 200px;
          color: darkblue;
          font-size:18px ;

      }
      button{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          font-family: 'Open Sans', sans-serif;
          font-size: 20px;
          border: none;
          cursor: pointer;
      }
      .btn{
          background-color: darkblue;
          color: white;
          text-align: center;
          border-radius: 30px;
          width: 220px;
          display: block;
          text-decoration: none;
          height: 50px;
          line-height: 50px;
          margin-top: 10px;
          margin-bottom: 10px;
          text-decoration: none;
      }

      /*mobile*/
      @media(max-width: 992px){
          .flex-container{
              flex-direction: column;
          }
          .apresentação{
              flex-direction: column-reverse;
          }

      }
  </style>
<body>
<header>
  <div class="flex-container menu">
    <div>
      <ul class="list-items">
        <h1>
          <li><a><%= link_to "GServicesES", root_path%></a></li>
        </h1>
      </ul>
    </div>

  </div>
</header>

<div class="flex-container apresentação">
  <div class="texto-apresentação">
    <ul class="list-items">
      <li> <%= render @trabalhador %></li>
      <li class="btn"><%= link_to "Editar este Trabalhador", edit_trabalhador_path(@trabalhador) %> </li>
      <li class="btn"> <%= link_to "Ver todos os Trabalhadors", trabalhadors_path %></li>
      <li><%= button_to "Apagar Trabalhador", @trabalhador, method: :delete %></li>
    </ul>
  </div>
</div>
</body>